### ISSUE TITLE
cronjob doesn't consider timezones

### ISSUE THREAD

**Issue by mmenschig** [kmenschig/Weather#1]
Currently, the script is set to run via cronjob every 1pm GMT+1 (can that be confirmed?)

Problem I see is when executing the script, other locations such as PWS:IMANIZAL5 will have their data retrieved at night, possibly returning unforeseen / not considered weather data such as lower temperatures etc.

The question therefore is:
1. Can we confirm that the cronjob does not need to be adjusted?
2. Does this require fixing?

**Comment by kmenschig** [comment]
(env) klaus@klaus-Precision-M6800:~/Documents/Projects/Weather$ git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Username for 'https://github.com': kmenschig
Password for 'https://kmenschig@github.com':
To https://github.com/kmenschig/cologneWeather.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to '
https://github.com/kmenschig/cologneWeather.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by mmenschig** [comment]
Closing this. Seems like this is resolved.
